AWSTemplateFormatVersion: '2010-09-09'
Description: Auto Scaling Group module for a 3-tier architecture

Parameters:
  EnvironmentName:
    Type: String
    Default: demo
  LaunchTemplateId:
    Type: String
  Ec2SubnetIds:
    Type: CommaDelimitedList
  TargetGroupArn:
    Type: String

Resources:
  DemoAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: !Sub ${EnvironmentName}-asg
      VPCZoneIdentifier: !Ref Ec2SubnetIds
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplateId
        Version: !GetAtt LaunchTemplate.LatestVersionNumber
      MinSize: 1
      MaxSize: 2
      DesiredCapacity: 1
      TargetGroupARNs:
        - !Ref TargetGroupArn
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-asg
          PropagateAtLaunch: true

  ScaleOutPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AutoScalingGroupName: !Ref DemoAutoScalingGroup
      PolicyType: TargetTrackingScaling
      TargetTrackingConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: ASGAverageCPUUtilization
        TargetValue: 50.0

Outputs:
  AutoScalingGroupName:
    Value: !Ref DemoAutoScalingGroup
